### ISSUE TITLE
Debug why Ansible service module does not seem to work

### ISSUE THREAD

**Issue by mikeanthonywild** [sdcc-sh/sdcc-ansible#13]
For example:

```yaml
- name: Start jails
  service:
    name: jail
    state: started
  become: yes
```

Results in:

```
TASK [Start jails]
ok: [vpsib9kvzy.sdcc.sh]
```

However, the service was not running beforehand, so the expected output should actually be `changed`. Need to investigate how the `service` module works, because it feels like it's not doing the correct thing here.
